apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - name: MyFirstProdContainer
      imagePullPolicy: Always
      applicationPorts: []
      cpuRequestMili: 100
      cpuLimitMili: 2000
      memoryRequestMb: 100
      memoryLimitMb: 1000
      command: []
      args: []
      healthChecks:
        - probeType:
            - readinessProbe
            - livenessProbe
          initialDelaySeconds: 30
          timeoutSeconds: 30
          periodSeconds: 30
          failureThreshold: 30
          httpGet:
            path: dsfsdf
            port: '22323'
            httpHeaders: []
          tcpSocket: {}
          exec: {}
        - probeType:
            - startupProbe
          initialDelaySeconds: 30
          timeoutSeconds: 30
          periodSeconds: 30
          failureThreshold: 30
          httpGet: {}
          tcpSocket:
            port: '5555'
          exec: {}
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: TestApp
    version: v0.0.1
    applicationId: app_f86e97a6-bfb9-4234-8502-887b0a2060b3
    projectId: project_81c3f610-98b2-4272-8a86-98a43e863b3d
    organizationId: org_5a158cfc-0d2c-467a-9217-db8b233a1b42
    environmentId: env_a1cfb8d4-f1c8-40ae-8772-a326d79b0d67
    environmentName: prod
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: TestApp
  cronTab: ''
  serviceType: ClusterIP
  namespace: hello-prod
