apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: myfirstapp
    applicationId: app_a293944d-4d75-46e2-893a-4b9cde9869c7
    version: v0.0.1
  name: myfirstapp
spec:
  selector:
    app: myfirstapp
