apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp
  labels:
    app: testapp
    applicationId: app_f86e97a6-bfb9-4234-8502-887b0a2060b3
    version: v0.0.1
spec:
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
