apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  labels:
    app: hello
    applicationId: app_0de4ba22-f99a-468a-9dd0-02e945efcb66
    version: v0.0.1
spec:
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
