apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: hello
    applicationId: app_0de4ba22-f99a-468a-9dd0-02e945efcb66
    version: v0.0.1
  name: hello
spec:
  selector:
    app: hello
