apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - name: MyContainer
      imagePullPolicy: Always
      applicationPorts: []
      cpuRequestMili: 400
      cpuLimitMili: 2000
      memoryRequestMb: 100
      memoryLimitMb: 1000
      command:
        - sdsd
      args: []
      healthChecks:
        - probeType:
            - readinessProbe
          initialDelaySeconds: 30
          timeoutSeconds: 49
          periodSeconds: 52
          failureThreshold: 54
          httpGet:
            path: newpath
            port: '4444'
            httpHeaders:
              - name: newkey
                value: value
          tcpSocket: {}
          exec: {}
          successThreshold: 52
        - probeType:
            - livenessProbe
          initialDelaySeconds: 68
          timeoutSeconds: 30
          periodSeconds: 30
          failureThreshold: 30
          httpGet: {}
          tcpSocket:
            port: '4444'
          exec: {}
          successThreshold: 71
        - probeType:
            - startupProbe
          initialDelaySeconds: 30
          timeoutSeconds: 30
          periodSeconds: 30
          failureThreshold: 30
          httpGet: {}
          tcpSocket: {}
          exec:
            command:
              - fdgfdg
    - name: MySecond Container
      imagePullPolicy: Always
      applicationPorts: []
      cpuRequestMili: 100
      cpuLimitMili: 2000
      memoryRequestMb: 100
      memoryLimitMb: 1000
      command:
        - asdsad
      args:
        - dsffd
      healthChecks: []
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: TestApp
    version: v0.0.1
    applicationId: app_f86e97a6-bfb9-4234-8502-887b0a2060b3
    projectId: project_81c3f610-98b2-4272-8a86-98a43e863b3d
    organizationId: org_5a158cfc-0d2c-467a-9217-db8b233a1b42
    environmentId: env_425a0be3-9248-4cd5-b652-a5df20b6cb26
    environmentName: dev
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: TestApp
  cronTab: ''
  serviceType: ClusterIP
  namespace: hello-dev
