apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: latest
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts: []
      healthChecks:
        - probeType:
            - readinessProbe
          initialDelaySeconds: 52
          timeoutSeconds: 30
          periodSeconds: 30
          failureThreshold: 30
        - probeType:
            - livenessProbe
            - startupProbe
          initialDelaySeconds: 103
          timeoutSeconds: 30
          periodSeconds: 30
          failureThreshold: 30
      name: myfirstapp-main
      imagePullPolicy: Always
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: MyFirstApp
    version: v0.0.1
    applicationId: app_a293944d-4d75-46e2-893a-4b9cde9869c7
    projectId: project_81c3f610-98b2-4272-8a86-98a43e863b3d
    organizationId: org_5a158cfc-0d2c-467a-9217-db8b233a1b42
    environmentId: env_24e6869a-c598-4012-823a-1e8b56c09bcd
    environmentName: staging
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: MyFirstApp
  cronTab: ''
  serviceType: ClusterIP
  namespace: hello-staging
